language: node_js
sudo: false
node_js: stable
install:
- npm install vue-cli -g
- vue init nuxt-community/typescript-template my-project
- npm install
script:
- npm run build
notifications:
  email: false
